services:
  translator:
    build: .
    container_name: laravel-translator
    ports:
      - "3005:3005"
    volumes:
      - type: bind
        source: ./input
        target: /app/input
      - type: bind
        source: ./output
        target: /app/output
      - type: bind
        source: ./app
        target: /app/app
      - type: bind
        source: ./public
        target: /app/public

    working_dir: /app/app
    command: node server.cjs
